spring:
  profiles:
    active: ${PROFILE}
  config:
    import: application-secret.properties
  web:
    resources:
      add-mappings: false

oauth:
  kakao:
    redirect-uri: ${KAKAO_REDIRECT_URL}
    client-id: ${KAKAO_REST_API_KEY}