spring:
  config:
    import: application-secret.properties
  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cone-local-db;DATABASE_TO_UPPER=FALSE;mode=mysql
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

oauth:
  kakao:
    redirect-uri: ${KAKAO_REDIRECT_URL}
    client-id: ${KAKAO_REST_API_KEY}

