spring:
  config:
    import:
      - classpath:application-secret.properties
      - classpath:external.yml
      - classpath:socket.yml
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

server:
  port: 443
  ssl:
    key-store-type: ${KEY_STORE_TYPE}
    key-store: ${KEY_STORE_PATH}
    key-store-password: ${SSL_PASSWORD}
  servlet:
    session:
      cookie:
        same-site: None
        secure: true