spring:
  config:
    import: application-secret.properties
  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

oauth:
  kakao:
    redirect-uri: ${KAKAO_REDIRECT_URL}
    client-id: ${KAKAO_REST_API_KEY}